### ISSUE TITLE
Comment characters within brackets

### ISSUE THREAD

**Issue by mblackgeo** [cschreib/sublime-idl#3] opened 2017-03-24 13:55 UTC
Comment characters are not respected inside brackets. 

Simple example:

    array = [ 1, $
             ;3, $
             5]

**Comment by cschreib** [comment] 2017-03-25 18:13
This code sample is highlighted correctly on my side:
![screenshot-area-2017-03-25-191224](https://cloud.githubusercontent.com/assets/2236577/24324898/06dea898-118f-11e7-8955-1ce8da67ff46.png)

If you see the same thing on your end, can you describe more clearly what the problem is?

**Comment by cschreib** [comment] 2017-03-25 19:06
Oh sorry, I just realized I had fixed that in an old commit (b771dc397b2f5b97d50b810ffe34f14e19120152) and never pushed it in a release. So this will be fixed in the next release!

**Closed as completed by cschreib** 2017-03-25 19:06 UTC
